spring.application.name=notificaciones
spring.config.import=secrets.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.whatsapp.from=whatsapp:+14155238886
